#!/usr/bin/env bash

# Written with Claude

# micro-ROS's libmicroros.mk clones ~29 repos from moving branches, so a cold
# build is not reproducible: the sources drift and eventually stop compiling.
# This pins them.
#
#   scripts/microros-pin.sh lock [DATE]   resolve each branch to a commit -> microros.lock
#   scripts/microros-pin.sh seed          clone the pinned commits into place
#
# seed works because libmicroros.mk guards both workspaces behind file targets
# (micro_ros_src/src and micro_ros_dev/install) with no prerequisites -- make
# skips the clone recipes entirely when those already exist.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
COMPONENT="$REPO/components/micro_ros_espidf_component"
MAKEFILE="$COMPONENT/libmicroros.mk"
LOCKFILE="$REPO/microros.lock"

die() { echo "microros-pin.sh: $*" >&2; exit 1; }

# emits "workspace path url branch" for every clone in libmicroros.mk, tagging
# the embeddedRTPS pair so seed can skip it (we build the microxrcedds middleware)
parse_clones() {
    awk '
        /^\$\(EXTENSIONS_DIR\)\/micro_ros_dev\/install:/ { ws = "dev"; next }
        /^\$\(EXTENSIONS_DIR\)\/micro_ros_src\/src:/     { ws = "src"; next }
        /^\$\(EXTENSIONS_DIR\)\// { ws = "" }
        ws && /git clone/ {
            b = ""; url = ""; path = ""
            for (i = 1; i <= NF; i++) {
                if ($i == "-b") b = $(i + 1)
                if ($i ~ /^https?:\/\//) { url = $i; path = $(i + 1) }
            }
            gsub(/;$/, "", path); gsub(/;$/, "", url)
            if (url == "" || path == "") next
            if (url ~ /embeddedRTPS|rmw_embeddedrtps/) print "ertps", path, url, b
            else print ws, path, url, b
        }
    ' "$MAKEFILE"
}

PIN_TMP=""
cleanup() { [ -n "$PIN_TMP" ] && rm -rf "$PIN_TMP"; return 0; }
trap cleanup EXIT

cmd_lock() {
    local before="${1:-}" sha n=0
    PIN_TMP="$(mktemp -d)"

    : > "$LOCKFILE.tmp"
    echo "# generated by scripts/microros-pin.sh -- do not edit by hand" >> "$LOCKFILE.tmp"
    echo "# workspace path url branch sha" >> "$LOCKFILE.tmp"
    [ -n "$before" ] && echo "# resolved at branch state as of $before" >> "$LOCKFILE.tmp"

    while read -r ws path url branch; do
        [ -z "${ws:-}" ] && continue
        n=$((n + 1))
        echo "microros-pin.sh: resolving $path ($branch)" >&2
        git clone --quiet --filter=blob:none --no-checkout "$url" "$PIN_TMP/$n" 2>/dev/null \
            || die "clone failed: $url"
        if [ -n "$before" ]; then
            sha="$(git -C "$PIN_TMP/$n" rev-list -n 1 --before="$before" "origin/$branch")"
        else
            sha="$(git -C "$PIN_TMP/$n" rev-parse "origin/$branch")"
        fi
        [ -n "$sha" ] || die "no commit for $url on $branch before $before"
        echo "$ws $path $url $branch $sha" >> "$LOCKFILE.tmp"
    done < <(parse_clones)

    mv "$LOCKFILE.tmp" "$LOCKFILE"
    echo "microros-pin.sh: wrote $LOCKFILE ($n repos)" >&2
}

clone_pinned() {
    local dest="$1" path url sha want="$2"
    while read -r ws p u b s; do
        case "$ws" in \#*|"") continue ;; esac
        [ "$ws" = "$want" ] || continue
        path="$p"; url="$u"; sha="$s"
        git clone --quiet --filter=blob:none --no-checkout "$url" "$dest/$path"
        git -C "$dest/$path" checkout --quiet "$sha"
    done < "$LOCKFILE"
}

cmd_seed() {
    [ -f "$LOCKFILE" ] || die "no $LOCKFILE -- run 'microros-pin.sh lock' first"

    if [ -d "$COMPONENT/micro_ros_src/src" ]; then
        echo "microros-pin.sh: micro_ros_src already seeded" >&2
    else
        echo "microros-pin.sh: seeding micro_ros_src from lock" >&2
        mkdir -p "$COMPONENT/micro_ros_src"
        clone_pinned "$COMPONENT/micro_ros_src" src

        # mirrors the COLCON_IGNORE / extra_packages tail of libmicroros.mk's
        # micro_ros_src/src recipe. upstream chains these with ';' so a package
        # that no longer exists at the pinned commit is skipped, not fatal --
        # rcl_logging_log4cxx is already gone from humble
        local s="$COMPONENT/micro_ros_src/src" ignore
        for ignore in rosidl/rosidl_typesupport_introspection_cpp \
                      rcl_logging/rcl_logging_log4cxx \
                      rcl_logging/rcl_logging_spdlog \
                      rclc/rclc_examples \
                      rcl/rcl_yaml_param_parser; do
            if [ -d "$s/$ignore" ]; then
                touch "$s/$ignore/COLCON_IGNORE"
            else
                echo "microros-pin.sh: no $ignore at pinned commit -- skipping" >&2
            fi
        done
        cp -rf "$COMPONENT/extra_packages" "$s/extra_packages" || :
    fi

    if [ -d "$COMPONENT/micro_ros_dev/install" ]; then
        echo "microros-pin.sh: micro_ros_dev already seeded" >&2
    else
        echo "microros-pin.sh: seeding + building micro_ros_dev from lock" >&2
        mkdir -p "$COMPONENT/micro_ros_dev"
        clone_pinned "$COMPONENT/micro_ros_dev" dev
        ( cd "$COMPONENT/micro_ros_dev" && colcon build --cmake-args \
              -DBUILD_TESTING=OFF -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=gcc )
    fi
}

case "${1:-}" in
    lock) shift; cmd_lock "${1:-}" ;;
    seed) cmd_seed ;;
    *) die "usage: microros-pin.sh {lock [DATE] | seed}" ;;
esac
